name: python312-implementation
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandas=2.1.4
  - numpy=1.25.2
  - scikit-learn=1.3.2
  - cryptography=41.0.7
  - pip
  - pip:
    - rdflib==7.0.0
    - pyshacl==0.23.2